# Use this metricPrefix only if SIM is enabled
metricPrefix: "Custom Metrics|Windows Service Monitor Extension"

#Use this metricPrefix when SIM is not enabled
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<ComponentID>|Custom Metrics|Windows Service Monitor Extension"

services: ["XblGameSave", "Ifsvc", "Dhcp"]
serviceRegex: []

# number of concurrent tasks
numberOfThreads: 20
encryptionKey: welcome

metrics:
- UpTimeInSec:
- ServiceStatus:


# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "controller"
  controllerPort: 8080
  account: "customer1"
  username: "user"
  password: "welcome"
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""
